fernetKey: clVidlZBUGY3c1k1NUtaQjYzZ0s2Vmx5YWRnUXRTZjE=
webserverSecretKey: clVidlZBUGY3c1k1NUtaQjYzZ0s2Vmx5YWRnUXRTZjE=
executor: "KubernetesExecutor"

dags:
  gitSync:
    enabled: true
    repo: https://github.com/danhenriquex/Kubernetes-for-Data-Engineering.git
    branch: main
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"